"""Ingest external data sources (clubelo today; understat/fbref/oddsportal deferred).

Usage::

    nutmeg-ingest-external --source clubelo
    nutmeg-ingest-external --source clubelo --refresh         # re-fetch even if cached
    nutmeg-ingest-external --source clubelo --teams Arsenal,Liverpool

The clubelo source iterates over EVERY team in our V4 historical-matches dataset
(``data/historical_sources/football_data_co_uk/``) and caches one parquet per
team under ``data/external/clubelo/<team>.parquet``. A coverage card is written
to ``docs/v5_external_data_coverage.md`` summarizing which teams were resolved.

Deferred sources (understat/fbref/oddsportal) raise a clear error pointing to
their module docstring so the user/CI sees why the path is blocked.
"""
from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

import pandas as pd

from nutmeg.v4.data.ingest import load_all_matches
from nutmeg.v4.data.sources import clubelo, fbref, oddsportal, understat


log = logging.getLogger("ingest_external")
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")


REPO_ROOT = Path(__file__).resolve().parents[6]  # apps/api/src/nutmeg/v4/cli → repo root
HISTORICAL_ROOT = REPO_ROOT / "data" / "historical_sources" / "football_data_co_uk"
COVERAGE_CARD = REPO_ROOT / "docs" / "v5_external_data_coverage.md"


def _collect_v4_teams() -> dict[str, list[str]]:
    """Return {competition_code: [unique team_canonical names]}."""
    df = load_all_matches(HISTORICAL_ROOT)
    out: dict[str, list[str]] = {}
    for league in df["league"].dropna().unique():
        teams = sorted(
            set(df.loc[df["league"] == league, "home_team"].dropna().unique())
            | set(df.loc[df["league"] == league, "away_team"].dropna().unique())
        )
        out[str(league)] = teams
    return out


def _flatten_teams(teams_by_league: dict[str, list[str]]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for teams in teams_by_league.values():
        for t in teams:
            if t not in seen:
                seen.add(t)
                out.append(t)
    return out


def _ingest_clubelo(teams: list[str], refresh: bool) -> pd.DataFrame:
    log.info("Ingesting clubelo history for %d teams (refresh=%s)", len(teams), refresh)
    hist = clubelo.ingest_teams(teams, refresh=refresh)
    log.info("Clubelo ingest done: %d total rows", len(hist))
    return hist


def _write_coverage_card(
    teams_by_league: dict[str, list[str]],
    clubelo_hist: pd.DataFrame,
) -> None:
    """Write a markdown card showing which teams resolved per source."""
    COVERAGE_CARD.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = []
    lines.append("# V5 External Data Coverage")
    lines.append("")
    lines.append(f"_Generated by `nutmeg-ingest-external` from {len(clubelo_hist)} rows_")
    lines.append("")
    lines.append("## Clubelo")
    lines.append("")
    lines.append("| Competition | Teams (V4) | Clubelo resolved | Coverage |")
    lines.append("|---|---:|---:|---:|")
    resolved_teams = set(clubelo_hist["team_canonical"].dropna().unique())
    total_v4 = 0
    total_hit = 0
    for league in sorted(teams_by_league):
        teams = teams_by_league[league]
        hit = sum(1 for t in teams if t in resolved_teams)
        total_v4 += len(teams)
        total_hit += hit
        pct = f"{(hit / max(len(teams), 1)) * 100:.1f}%"
        lines.append(f"| {league} | {len(teams)} | {hit} | {pct} |")
    lines.append(f"| **Total** | **{total_v4}** | **{total_hit}** | **{(total_hit / max(total_v4, 1)) * 100:.1f}%** |")
    lines.append("")
    lines.append("## Deferred Sources (W12 decision)")
    lines.append("")
    lines.append("| Source | Status | Notes |")
    lines.append("|---|---|---|")
    lines.append("| understat | 🚫 blocked | Site moved to JS-rendered; `understat` pkg + httpx scrape both fail. See `sources/understat.py` docstring. |")
    lines.append("| fbref | 🚫 blocked | HTTP 403 on all User-Agents. See `sources/fbref.py` docstring. |")
    lines.append("| OddsPortal | 🚫 deferred | Cloudflare + JS shell. Use football-data.co.uk B365 opening odds for W5 instead. |")
    lines.append("")
    lines.append("## Next steps")
    lines.append("")
    lines.append("1. **W4 xG-lite**: derive a prematch xG approximation from football-data.co.uk's `home_shots` / `home_shots_on_target` columns (already in our DataFrame).")
    lines.append("2. **W5 market dynamics**: use football-data.co.uk's `B365CH/CD/CA` opening odds vs `PSCH/PSCD/PSCA` closing odds — no external fetch needed.")
    lines.append("3. **W6+ ensemble**: extends V4 GBM with XGBoost + CatBoost, fully offline using existing features + clubelo.")
    lines.append("4. **W12 paid-data decision**: if log-loss target ≤ 0.9937 is met without paid xG, defer purchase indefinitely.")
    lines.append("")
    COVERAGE_CARD.write_text("\n".join(lines))
    log.info("Wrote coverage card to %s", COVERAGE_CARD)


def parse_args(argv: list[str]) -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Ingest external data sources for V5.")
    p.add_argument(
        "--source",
        choices=["clubelo", "understat", "fbref", "oddsportal", "all"],
        required=True,
        help="Source to fetch.",
    )
    p.add_argument(
        "--teams",
        default=None,
        help="Comma-separated list of canonical team names (defaults to all V4 teams).",
    )
    p.add_argument(
        "--refresh",
        action="store_true",
        help="Force re-fetch even if cached parquet exists.",
    )
    p.add_argument(
        "--skip-coverage-card",
        action="store_true",
        help="Don't rewrite docs/v5_external_data_coverage.md.",
    )
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv if argv is not None else sys.argv[1:])

    if args.source in {"understat", "fbref", "oddsportal"}:
        adapter = {"understat": understat, "fbref": fbref, "oddsportal": oddsportal}[args.source]
        try:
            adapter.fetch_match_summary("EPL", 2024) if args.source == "fbref" else (
                adapter.fetch_opening_odds("EPL", 2024) if args.source == "oddsportal" else adapter.fetch_league_season("EPL", 2024)
            )
        except RuntimeError as exc:
            log.error("%s: %s", args.source, exc)
            return 2

    teams_by_league = _collect_v4_teams()
    all_teams = (
        [t.strip() for t in args.teams.split(",")] if args.teams else _flatten_teams(teams_by_league)
    )

    if args.source in {"clubelo", "all"}:
        hist = _ingest_clubelo(all_teams, refresh=args.refresh)
        if not args.skip_coverage_card:
            _write_coverage_card(teams_by_league, hist)
        log.info("Clubelo: %d unique teams covered", hist["team_canonical"].nunique())

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
