"""V11 Phase 0 #5 — sanity tests for the MCMC exploration script.

The full end-to-end run is ~12 seconds (too slow for the unit suite),
so these tests exercise:
  - The pure helpers (fingerprint-free): loglik, predict, log-loss
  - That the runner module imports cleanly + exposes the expected surface
  - That the report template renders without TypeError on a stubbed result

The actual MCMC verdict lives in docs/v11_phase0_mcmc_report.md and
should be regenerated by running the script directly.
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pytest


REPO_ROOT = Path(__file__).resolve().parents[2]
NOTEBOOK_DIR = REPO_ROOT / "notebooks"
sys.path.insert(0, str(NOTEBOOK_DIR))


@pytest.fixture(scope="module")
def mod():
    """Import the exploration module once per test file."""
    import importlib
    return importlib.import_module("v11_phase0_mcmc_exploration")


class TestModuleSurface:
    def test_imports_clean(self, mod):
        assert hasattr(mod, "main")
        assert hasattr(mod, "run_comparison")
        assert hasattr(mod, "render_report")

    def test_helpers_exposed(self, mod):
        for fn in ("load_epl_season", "build_dims", "fit_mle",
                   "mh_sample", "fit_map", "unpack", "compute_lambdas",
                   "predict_3way_from_lambdas", "log_loss_3way",
                   "outcome_label", "market_probs",
                   "effective_sample_size", "r_hat"):
            assert hasattr(mod, fn), f"missing helper {fn}"


class TestPredictionsHelper:
    def test_3way_probs_sum_to_1(self, mod):
        ph, pd_, pa = mod.predict_3way_from_lambdas(1.5, 1.2, -0.10)
        assert abs(ph + pd_ + pa - 1.0) < 1e-9

    def test_higher_home_lambda_increases_home_prob(self, mod):
        ph_lo, _, _ = mod.predict_3way_from_lambdas(0.8, 1.5, -0.10)
        ph_hi, _, _ = mod.predict_3way_from_lambdas(2.5, 1.5, -0.10)
        assert ph_hi > ph_lo

    def test_outcome_label(self, mod):
        assert mod.outcome_label(2, 1) == 0  # home win
        assert mod.outcome_label(1, 1) == 1  # draw
        assert mod.outcome_label(0, 3) == 2  # away win


class TestLogLoss:
    def test_perfect_prediction_zero_loss(self, mod):
        # If we always say P(actual) = 1, log-loss = 0
        outcomes = np.array([0, 1, 2, 0])
        probs = np.zeros((4, 3))
        for i, o in enumerate(outcomes):
            probs[i, o] = 1.0
        ll = mod.log_loss_3way(probs, outcomes)
        assert ll < 1e-9

    def test_uniform_is_log3(self, mod):
        outcomes = np.array([0, 1, 2])
        probs = np.full((3, 3), 1.0 / 3.0)
        ll = mod.log_loss_3way(probs, outcomes)
        assert abs(ll - np.log(3.0)) < 1e-9


class TestMarketProbs:
    def test_dewedged(self, mod):
        # 1/2 + 1/4 + 1/4 = 1.0 already; should normalize trivially
        psh = np.array([2.0]); psd = np.array([4.0]); psa = np.array([4.0])
        p = mod.market_probs(psh, psd, psa)
        assert p.shape == (1, 3)
        assert abs(p.sum() - 1.0) < 1e-9
        assert abs(p[0, 0] - 0.5) < 1e-9

    def test_normalization_removes_overround(self, mod):
        # Booky-style overround — sum of inverses > 1.0
        psh = np.array([2.0]); psd = np.array([3.5]); psa = np.array([4.0])
        p = mod.market_probs(psh, psd, psa)
        assert abs(p.sum() - 1.0) < 1e-9


class TestReportRendering:
    """The template should produce sensible markdown for various verdict states."""

    def _stub_result(self, **overrides):
        base = dict(
            n_train=380, n_test=300, n_test_dropped=80,
            n_teams=20, n_params=42, n_chains=4, n_samples_per_chain=3000,
            mle_time_s=0.05, mcmc_time_s=10.0, mcmc_time_ratio=200.0,
            uniform_ll=1.0986, market_ll=1.034,
            mle_ll=1.063, mcmc_ll=1.057,
            delta_mcmc_mle=-0.006, delta_mcmc_market=0.023, delta_mle_market=0.029,
            min_ess=200, median_ess=400, max_rhat=1.04, median_rhat=1.02,
            ess_home_adv=500, ess_rho=300, rhat_home_adv=1.01, rhat_rho=1.04,
            posterior_home_adv=0.21, posterior_rho=-0.08,
            mle_home_adv=0.20, mle_rho=-0.10,
        )
        base.update(overrides)
        return base

    def test_renders_when_fully_converged_and_mcmc_wins(self, mod):
        md = mod.render_report(self._stub_result())
        assert "🟢 MCMC WINS" in md
        assert "DC MLE" in md
        assert "1.0630" in md or "1.063" in md

    def test_renders_when_borderline_converged(self, mod):
        md = mod.render_report(self._stub_result(max_rhat=1.08, min_ess=150))
        assert "🟡 MCMC SUGGESTIVE" in md or "INCONCLUSIVE" not in md

    def test_renders_when_not_converged(self, mod):
        md = mod.render_report(self._stub_result(max_rhat=1.5, min_ess=10))
        assert "🟡 INCONCLUSIVE" in md or "did not converge" in md

    def test_renders_when_tie(self, mod):
        md = mod.render_report(self._stub_result(
            mcmc_ll=1.0631, delta_mcmc_mle=0.0001,
        ))
        assert "TIE" in md or "indistinguishable" in md

    def test_renders_when_mcmc_loses(self, mod):
        md = mod.render_report(self._stub_result(
            mcmc_ll=1.080, delta_mcmc_mle=+0.017,
        ))
        assert "🔴 MCMC LOSES" in md


class TestReportArtifact:
    """The report must exist on disk after the script has been run.
    (Generated as part of P1 work; we don't regenerate here — too slow.)"""

    def test_report_exists(self):
        report = REPO_ROOT / "docs" / "v11_phase0_mcmc_report.md"
        assert report.exists(), (
            "Run notebooks/v11_phase0_mcmc_exploration.py once to generate "
            "the report before committing."
        )

    def test_report_has_verdict_section(self):
        report = (REPO_ROOT / "docs" / "v11_phase0_mcmc_report.md").read_text()
        assert "## Verdict" in report
        assert "## Out-of-sample log-loss" in report
        assert "## Recommendation" in report


class TestNotebookExists:
    def test_ipynb_exists(self):
        nb = REPO_ROOT / "notebooks" / "v11_phase0_mcmc_exploration.ipynb"
        assert nb.exists()

    def test_ipynb_is_valid_json(self):
        import json
        nb = REPO_ROOT / "notebooks" / "v11_phase0_mcmc_exploration.ipynb"
        data = json.loads(nb.read_text())
        assert data.get("nbformat") == 4
        assert "cells" in data
        assert len(data["cells"]) >= 5  # at least intro + 4 working cells
