import { z } from "zod";

export const probabilityItemSchema = z.object({
  label: z.string(),
  probability: z.number().min(0).max(1),
  marketProbability: z.number().min(0).max(1).optional(),
  isHighlighted: z.boolean().optional(),
});

const upsetContributionSchema = z.object({
  key: z.string(),
  label: z.string(),
  score: z.number().min(0).max(100),
  description: z.string(),
});

const upsetExplanationGroupSchema = z.object({
  title: z.string(),
  items: z.array(z.string()),
});

export const matchPredictionSchema = z.object({
  fixtureId: z.string(),
  competitionId: z.string(),
  competitionName: z.string(),
  kickoffTimeUtc: z.string(),
  homeTeam: z.object({ teamId: z.string(), name: z.string() }),
  awayTeam: z.object({ teamId: z.string(), name: z.string() }),
  status: z.enum(["scheduled", "stale", "beta"]),
  modelStatus: z.enum(["beta", "production"]),
  modelVersion: z.string(),
  featureVersion: z.string(),
  calibrationVersion: z.string(),
  predictionTimeUtc: z.string(),
  dataQualityScore: z.number().min(0).max(100),
  dataQualityGrade: z.enum(["A", "B", "C", "D"]),
  dataFreshness: z
    .object({
      stale: z.boolean(),
      fallbackUsed: z.boolean(),
      oddsAvailable: z.boolean(),
      oddsFreshEnough: z.boolean(),
      oddsMarketTypes: z.array(z.string()),
      oddsSnapshotTimeUtc: z.string().nullable(),
      oddsSnapshotLagHours: z.number().nullable(),
      lineupAvailable: z.boolean(),
      lineupFreshEnough: z.boolean(),
      lineupSnapshotTimeUtc: z.string().nullable(),
      lineupSnapshotLagHours: z.number().nullable(),
      injuryAvailable: z.boolean(),
      injuryFreshEnough: z.boolean(),
      injurySnapshotTimeUtc: z.string().nullable(),
      injurySnapshotLagHours: z.number().nullable(),
      messages: z.array(z.string()),
    })
    .optional(),
  confidence: z.enum(["low", "medium", "high"]),
  oneXTwo: z.array(probabilityItemSchema),
  cnHandicap: z.object({
    label: z.string(),
    items: z.array(probabilityItemSchema),
  }),
  asianHandicap: z.object({
    label: z.string(),
    items: z.array(probabilityItemSchema),
  }),
  europeanHandicap: z.object({
    label: z.string(),
    items: z.array(probabilityItemSchema),
  }),
  correctScores: z.array(
    z.object({
      score: z.string(),
      probability: z.number().min(0).max(1),
      optionKey: z.string(),
    }),
  ),
  scoreGrid: z.object({
    maxGoals: z.number().int().nonnegative(),
    grid: z.array(z.array(z.number().min(0).max(1))),
    tailMass: z.number().min(0).max(1),
    lambdaHome: z.number().nullable(),
    lambdaAway: z.number().nullable(),
  }),
  tailEvents: z.array(probabilityItemSchema),
  upsetAlerts: z.array(
    z.object({
      type: z.string(),
      label: z.string(),
      targetOutcome: z.string(),
      favorite: z.string().optional(),
      favoriteModelProbability: z.number().min(0).max(1).optional(),
      favoriteMarketProbability: z.number().min(0).max(1).optional(),
      modelProbability: z.number().min(0).max(1),
      marketProbability: z.number().min(0).max(1),
      probabilityGap: z.number(),
      favoriteFragilityScore: z.number().min(0).max(1),
      riskLevel: z.enum(["low", "medium", "medium_high", "high"]),
      explanations: z.array(z.string()),
      contributions: z.array(upsetContributionSchema).optional(),
      explanationGroups: z.array(upsetExplanationGroupSchema).optional(),
    }),
  ),
  keyFactors: z.object({
    model: z.array(z.string()),
    market: z.array(z.string()),
    lineup: z.array(z.string()),
    schedule: z.array(z.string()),
    uncertainty: z.array(z.string()),
  }),
});

export const parlayTicketSchema = z.object({
  recommendationId: z.string(),
  strategy: z.string(),
  passType: z.string(),
  isMultiple: z.boolean(),
  legs: z.array(
    z.object({
      fixtureId: z.string(),
      matchLabel: z.string(),
      market: z.string(),
      outcomes: z.array(z.string()),
    }),
  ),
  atomicBetCount: z.number().int().nonnegative(),
  unitStake: z.number().positive(),
  totalStake: z.number().nonnegative(),
  hitProbability: z.number().min(0).max(1),
  expectedPayout: z.number().nonnegative(),
  ev: z.number(),
  roi: z.number(),
  riskLevel: z.enum(["low", "medium", "medium_high", "high"]),
  riskScore: z.number().min(0).max(1),
  correlationPenalty: z.number().min(0).max(1),
  ruleValid: z.boolean(),
  explanations: z.array(z.string()),
  explanationJson: z.record(z.string(), z.unknown()),
  atomicBets: z.array(
    z.object({
      legs: z.array(
        z.object({
          fixtureId: z.string(),
          marketType: z.string(),
          outcome: z.string(),
          probability: z.number().min(0).max(1),
          odds: z.number().gt(1),
          line: z.number().nullable(),
        }),
      ),
      stake: z.number().positive(),
      probability: z.number().min(0).max(1),
      oddsProduct: z.number().gt(1),
      expectedPayout: z.number(),
      expectedValue: z.number(),
      roi: z.number(),
    }),
  ),
});

export const accuracyMetricSetSchema = z.object({
  logLoss: z.number().nullable(),
  brierScore: z.number().nullable(),
  ece: z.number().nullable(),
  sampleSize: z.number().int().nonnegative(),
});

export const accuracySummarySchema = z.object({
  logLoss: z.number().nullable(),
  brierScore: z.number().nullable(),
  ece: z.number().nullable(),
  sampleSize: z.number().int().nonnegative(),
  byMarket: z.record(z.string(), accuracyMetricSetSchema),
  byCompetition: z.array(
    accuracyMetricSetSchema.extend({
      competitionId: z.string(),
      competitionName: z.string(),
    }),
  ),
  calibrationBuckets: z.array(
    z.object({
      bucketStart: z.number().min(0).max(1),
      bucketEnd: z.number().min(0).max(1),
      averagePredictedProbability: z.number().min(0).max(1),
      actualFrequency: z.number().min(0).max(1),
      sampleSize: z.number().int().nonnegative(),
    }),
  ),
  errorTypes: z.array(
    z.object({
      tag: z.string(),
      label: z.string(),
      count: z.number().int().nonnegative(),
      share: z.number().min(0).max(1),
      examples: z.array(z.string()),
    }),
  ),
  modelComparisons: z.array(
    z.object({
      baselineModelVersion: z.string(),
      candidateModelVersion: z.string(),
      baselineLogLoss: z.number().nullable(),
      candidateLogLoss: z.number().nullable(),
      baselineBrierScore: z.number().nullable(),
      candidateBrierScore: z.number().nullable(),
      calibrationDelta: z.number().nullable(),
      sampleSize: z.number().int().nonnegative(),
      decision: z.enum(["promote_candidate", "keep_baseline", "needs_review"]),
      reasons: z.array(z.string()),
    }),
  ),
  modelVersion: z.string(),
  window: z.string(),
  filters: z.object({
    modelVersion: z.string(),
    competitionId: z.string(),
    market: z.string(),
    window: z.string(),
  }),
  generatedAtUtc: z.string(),
  stale: z.boolean(),
});

export const recommendationStrategyEvidenceSchema = z.object({
  strategy: z.string(),
  passType: z.string(),
  mode: z.string(),
  sampleSize: z.number().int().nonnegative(),
  settledRunCount: z.number().int().nonnegative(),
  hitCount: z.number().int().nonnegative(),
  totalStake: z.number().nonnegative(),
  grossPayout: z.number().nonnegative(),
  profitLoss: z.number(),
  roi: z.number().nullable(),
  hitRate: z.number().min(0).max(1).nullable(),
  averageExpectedRoi: z.number().nullable(),
  averageExpectedHitProbability: z.number().min(0).max(1).nullable(),
  averageHitCalibrationError: z.number().nullable(),
  meanAbsoluteHitCalibrationError: z.number().nonnegative().nullable(),
  firstEvaluationTimeUtc: z.string().nullable(),
  lastEvaluationTimeUtc: z.string().nullable(),
});

export const recommendationStrategyGovernanceSchema = z.object({
  generatedAtUtc: z.string(),
  items: z.array(
    z.object({
      candidateStrategy: z.string(),
      baselineStrategy: z.string(),
      passType: z.string(),
      mode: z.string(),
      candidateEvidence: recommendationStrategyEvidenceSchema,
      baselineEvidence: recommendationStrategyEvidenceSchema,
      decision: z.enum(["shadow_candidate", "keep_experiment"]),
      nextStatus: z.enum(["shadow", "experiment"]),
      reasons: z.array(z.string()),
      shouldRollback: z.boolean(),
      rollbackTargetStrategy: z.string().nullable(),
      rollbackReasons: z.array(z.string()),
      metricDeltas: z.object({
        roiDelta: z.number().nullable(),
        hitRateDelta: z.number().nullable(),
        calibrationErrorDelta: z.number().nullable(),
        expectedRoiDelta: z.number().nullable(),
      }),
      warnings: z.array(z.string()),
    }),
  ),
  stale: z.boolean(),
  fallbackUsed: z.boolean(),
});

export const providerOpsSchema = z.object({
  providers: z.array(
    z.object({
      providerName: z.string(),
      status: z.enum(["active", "pending_review", "research_only", "blocked", "expired"]),
      capabilities: z.array(z.string()),
      termsCheckedAtUtc: z.string().nullable(),
      commercialUseAllowed: z.boolean(),
      retentionAllowed: z.boolean(),
      allowedUse: z.string(),
      rateLimit: z.string().nullable(),
      historicalDataAllowed: z.boolean(),
      redistributionAllowed: z.boolean(),
      termsUrl: z.string().nullable(),
      lastReviewedAtUtc: z.string().nullable(),
      nextReviewDueAtUtc: z.string().nullable(),
      owner: z.string(),
      apiKeyEnvVar: z.string().nullable(),
      notes: z.string(),
    }),
  ),
  authorizationReviews: z.object({
    fetched: z.boolean(),
    stale: z.boolean(),
    fallbackUsed: z.boolean(),
    items: z.array(
      z.object({
        providerAuthorizationReviewId: z.number(),
        providerName: z.string(),
        reviewReference: z.string(),
        reviewStatus: z.enum(["approved", "research_only", "needs_review", "blocked"]),
        reviewedBy: z.string(),
        reviewedAtUtc: z.string(),
        termsUrl: z.string().nullable(),
        termsVersionHash: z.string().nullable(),
        allowedUse: z.string(),
        commercialUseAllowed: z.boolean(),
        retentionAllowed: z.boolean(),
        historicalDataAllowed: z.boolean(),
        redistributionAllowed: z.boolean(),
        rateLimit: z.string().nullable(),
        nextReviewDueAtUtc: z.string().nullable(),
        evidenceJson: z.record(z.string(), z.unknown()),
        notes: z.string(),
        createdAtUtc: z.string(),
      }),
    ),
  }),
  runtimeCredentials: z.object({
    fetched: z.boolean(),
    mockDryRunEnabled: z.boolean(),
    generatedAtUtc: z.string(),
    items: z.array(
      z.object({
        providerName: z.string(),
        capabilities: z.array(z.string()),
        apiKeyEnvVar: z.string().nullable(),
        runtimeEnvVar: z.string().nullable(),
        keyConfigured: z.boolean(),
        dryRunMode: z.enum(["local_only", "mock_sample", "real_provider", "blocked"]),
        commitMode: z.enum(["not_applicable", "ready", "blocked"]),
        safeToCallRealProvider: z.boolean(),
        mockDryRunEnabled: z.boolean(),
        requiresApiKeyForCommit: z.boolean(),
        nextAction: z.string(),
        notes: z.array(z.string()),
      }),
    ),
    stale: z.boolean(),
    fallbackUsed: z.boolean(),
  }),
  runtimeMonitoring: z.object({
    fetched: z.boolean(),
    generatedAtUtc: z.string(),
    summary: z.object({
      providerCount: z.number().int().nonnegative(),
      healthyCount: z.number().int().nonnegative(),
      degradedCount: z.number().int().nonnegative(),
      rateLimitedCount: z.number().int().nonnegative(),
      authFailedCount: z.number().int().nonnegative(),
      unavailableCount: z.number().int().nonnegative(),
      notConfiguredCount: z.number().int().nonnegative(),
      fallbackProviderCount: z.number().int().nonnegative(),
      averageLatencyMs: z.number().nonnegative().nullable(),
      latestObservedAtUtc: z.string().nullable(),
    }),
    alertLevel: z.enum(["ok", "P0", "P1", "P2"]),
    alerts: z.array(
      z.object({
        alertId: z.string(),
        severity: z.enum(["P0", "P1", "P2"]),
        providerName: z.string().nullable(),
        capability: z.string().nullable(),
        metric: z.string(),
        currentValue: z.union([z.number(), z.string()]).nullable(),
        threshold: z.union([z.number(), z.string()]).nullable(),
        message: z.string(),
        recommendedAction: z.string(),
      }),
    ),
    thresholds: z.object({
      providerLatencyP2Ms: z.number().int().nonnegative(),
      providerLatencyP1Ms: z.number().int().nonnegative(),
      providerErrorRateP1: z.number().min(0).max(1),
      providerPlanLimitP2: z.number().min(0).max(1),
      fallbackUsageRateP1: z.number().min(0).max(1),
    }),
    items: z.array(
      z.object({
        providerRuntimeSnapshotId: z.number().int().positive().nullable(),
        providerName: z.string(),
        capability: z.string(),
        probeStatus: z.enum([
          "not_configured",
          "key_configured",
          "ok",
          "limited",
          "auth_failed",
          "rate_limited",
          "unavailable",
          "adapter_planned",
        ]),
        keyConfigured: z.boolean(),
        liveProbe: z.boolean(),
        safeToCallRealProvider: z.boolean(),
        latencyMs: z.number().int().nonnegative().nullable(),
        errorRate: z.number().min(0).max(1).nullable(),
        successCount: z.number().int().nonnegative(),
        failureCount: z.number().int().nonnegative(),
        rateLimitRemaining: z.number().int().nonnegative().nullable(),
        quotaWindow: z.string().nullable(),
        fallbackUsed: z.boolean(),
        message: z.string(),
        nextAction: z.enum([
          "no_action",
          "configure_runtime_key",
          "review_provider_plan_limit",
          "check_provider_credentials",
          "retry_after_provider_recovery",
          "adapter_not_ready",
        ]),
        metadataJson: z.record(z.string(), z.unknown()),
        observedAtUtc: z.string(),
      }),
    ),
    stale: z.boolean(),
    fallbackUsed: z.boolean(),
  }),
  runtimeIncidents: z.object({
    fetched: z.boolean(),
    items: z.array(
      z.object({
        providerRuntimeIncidentReportId: z.number().int().positive(),
        alertLevel: z.enum(["ok", "P0", "P1", "P2"]),
        alertCount: z.number().int().nonnegative(),
        snapshotCount: z.number().int().nonnegative(),
        summaryJson: z.record(z.string(), z.unknown()),
        alertsJson: z.array(z.record(z.string(), z.unknown())),
        thresholdsJson: z.record(z.string(), z.unknown()),
        source: z.string(),
        createdBy: z.string(),
        metadataJson: z.record(z.string(), z.unknown()),
        incidentStatus: z.enum(["open", "acknowledged", "resolved", "ignored"]),
        acknowledgedBy: z.string().nullable(),
        acknowledgedAtUtc: z.string().nullable(),
        resolvedBy: z.string().nullable(),
        resolvedAtUtc: z.string().nullable(),
        resolutionNote: z.string().nullable(),
        notificationStatus: z.enum([
          "not_configured",
          "queued",
          "sent",
          "skipped",
          "failed",
        ]),
        notificationPayloadJson: z.record(z.string(), z.unknown()),
        updatedAtUtc: z.string().nullable(),
        createdAtUtc: z.string(),
      }),
    ),
    summary: z.object({
      lookbackDays: z.number().int().positive(),
      totalCount: z.number().int().nonnegative(),
      openCount: z.number().int().nonnegative(),
      acknowledgedCount: z.number().int().nonnegative(),
      resolvedCount: z.number().int().nonnegative(),
      ignoredCount: z.number().int().nonnegative(),
      activeCount: z.number().int().nonnegative(),
      p0Count: z.number().int().nonnegative(),
      p1Count: z.number().int().nonnegative(),
      p2Count: z.number().int().nonnegative(),
      notificationFailedCount: z.number().int().nonnegative(),
      latestCreatedAtUtc: z.string().nullable(),
      meanTimeToResolveMinutes: z.number().nonnegative().nullable(),
      trendBuckets: z.array(
        z.object({
          bucketDate: z.string(),
          totalCount: z.number().int().nonnegative(),
          openCount: z.number().int().nonnegative(),
          acknowledgedCount: z.number().int().nonnegative(),
          resolvedCount: z.number().int().nonnegative(),
          ignoredCount: z.number().int().nonnegative(),
          activeCount: z.number().int().nonnegative(),
          p0Count: z.number().int().nonnegative(),
          p1Count: z.number().int().nonnegative(),
          p2Count: z.number().int().nonnegative(),
          notificationFailedCount: z.number().int().nonnegative(),
        }),
      ),
    }),
    filters: z.object({
      limit: z.number().int().positive(),
      offset: z.number().int().nonnegative(),
      lookbackDays: z.number().int().positive(),
      incidentStatus: z.enum(["all", "open", "acknowledged", "resolved", "ignored"]),
      alertLevel: z.enum(["all", "ok", "P0", "P1", "P2"]),
      notificationStatus: z.enum([
        "all",
        "not_configured",
        "queued",
        "sent",
        "skipped",
        "failed",
      ]),
      source: z.string().nullable(),
    }),
    limit: z.number().int().positive(),
    offset: z.number().int().nonnegative(),
    totalCount: z.number().int().nonnegative(),
    hasMore: z.boolean(),
    stale: z.boolean(),
    fallbackUsed: z.boolean(),
  }),
  apiKeyChecklist: z.object({
    fetched: z.boolean(),
    items: z.array(
      z.object({
        providerName: z.string(),
        nutmegRole: z.string(),
        priority: z.number().int().positive(),
        adapterStatus: z.enum(["supported_now", "adapter_planned"]),
        requiredEnvVar: z.string(),
        keyConfigured: z.boolean(),
        applyUrl: z.string(),
        docsUrl: z.string(),
        officialFreeTierNote: z.string(),
        freeTierFit: z.enum([
          "good_for_first_dry_run",
          "trial_required",
          "limited_for_soccer",
        ]),
        operatorAction: z.string(),
        sourceCheckedAtUtc: z.string(),
      }),
    ),
    generatedAtUtc: z.string(),
    stale: z.boolean(),
    fallbackUsed: z.boolean(),
  }),
  auditTrail: z.object({
    fetched: z.boolean(),
    items: z.array(
      z.object({
        providerOpsAuditEventId: z.number().int().positive(),
        eventType: z.string(),
        operatorName: z.string().nullable(),
        actionSurface: z.string(),
        targetType: z.string().nullable(),
        targetId: z.string().nullable(),
        outcome: z.enum(["success", "failure", "blocked"]),
        requestPath: z.string().nullable(),
        requestMethod: z.string().nullable(),
        metadataJson: z.record(z.string(), z.unknown()),
        createdAtUtc: z.string(),
      }),
    ),
    stale: z.boolean(),
    fallbackUsed: z.boolean(),
  }),
  runHistory: z.object({
    fetched: z.boolean(),
    items: z.array(
      z.object({
        providerOpsRunId: z.number().int().positive(),
        runName: z.string(),
        runType: z.string(),
        source: z.string(),
        status: z.enum(["success", "failure", "skipped"]),
        operatorName: z.string().nullable(),
        startedAtUtc: z.string().nullable(),
        completedAtUtc: z.string().nullable(),
        durationMs: z.number().int().nonnegative().nullable(),
        exitCode: z.number().int().nullable(),
        summaryJson: z.record(z.string(), z.unknown()),
        outputExcerpt: z.string().nullable(),
        metadataJson: z.record(z.string(), z.unknown()),
        createdAtUtc: z.string(),
      }),
    ),
    stale: z.boolean(),
    fallbackUsed: z.boolean(),
  }),
  readiness: z.array(
    z.object({
      competitionId: z.string(),
      competitionName: z.string(),
      targetStage: z.enum(["beta", "production"]),
      decision: z.enum(["beta_ready", "production_ready", "not_ready"]),
      dataQuality: z.object({
        score: z.number().min(0).max(100),
        grade: z.enum(["A", "B", "C", "D"]),
        parlayEligible: z.boolean(),
        components: z.object({
          fixtureReliability: z.number().min(0).max(1),
          oddsCoverage: z.number().min(0).max(1),
          lineupInjuryCoverage: z.number().min(0).max(1),
          historicalStatsCompleteness: z.number().min(0).max(1),
          providerConsistency: z.number().min(0).max(1),
          dataFreshness: z.number().min(0).max(1),
        }),
        messages: z.array(z.string()),
      }),
      reasons: z.array(z.string()),
      betaReady: z.boolean(),
      productionReady: z.boolean(),
    }),
  ),
  mappings: z.array(
    z.object({
      mappingId: z.number().int().positive(),
      provider: z.string(),
      entityType: z.string(),
      providerEntityId: z.string(),
      canonicalEntityId: z.string(),
      confidence: z.number().min(0).max(1),
      createdAtUtc: z.string(),
      updatedAtUtc: z.string(),
    }),
  ),
  mappingSummary: z.array(
    z.object({
      provider: z.string(),
      entityType: z.string(),
      mappingCount: z.number().int().nonnegative(),
      averageConfidence: z.number().min(0).max(1),
      minimumConfidence: z.number().min(0).max(1),
      latestUpdatedAtUtc: z.string(),
    }),
  ),
  mappingReview: z.object({
    dryRun: z.boolean(),
    asOfTimeUtc: z.string(),
    checkedMappingCount: z.number().int().nonnegative(),
    issueCount: z.number().int().nonnegative(),
    criticalCount: z.number().int().nonnegative(),
    warningCount: z.number().int().nonnegative(),
    infoCount: z.number().int().nonnegative(),
    issues: z.array(
      z.object({
        issueId: z.string(),
        issueType: z.enum([
          "low_confidence",
          "same_provider_canonical_collision",
          "stale_mapping",
        ]),
        severity: z.enum(["info", "warning", "critical"]),
        provider: z.string(),
        entityType: z.string(),
        canonicalEntityId: z.string(),
        providerEntityIds: z.array(z.string()),
        mappingIds: z.array(z.number().int().positive()),
        confidenceMin: z.number().min(0).max(1).nullable(),
        latestUpdatedAtUtc: z.string().nullable(),
        reasons: z.array(z.string()),
        recommendedAction: z.string(),
      }),
    ),
    stale: z.boolean(),
    fallbackUsed: z.boolean(),
  }),
  conflictGovernance: z.object({
    dryRun: z.boolean(),
    asOfTimeUtc: z.string(),
    checkedIssueCount: z.number().int().nonnegative(),
    conflictCount: z.number().int().nonnegative(),
    criticalCount: z.number().int().nonnegative(),
    warningCount: z.number().int().nonnegative(),
    infoCount: z.number().int().nonnegative(),
    providerConsistencyAfterConflicts: z.number().min(0).max(1),
    dataQualityScoreDelta: z.number().max(0),
    trustedPriorities: z.array(
      z.object({
        providerName: z.string(),
        capability: z.string(),
        priorityRank: z.number().int().positive(),
        reason: z.string(),
      }),
    ),
    events: z.array(
      z.object({
        sourceIssueId: z.string().nullable(),
        conflictType: z.enum([
          "provider_mapping_conflict",
          "provider_observation_conflict",
        ]),
        severity: z.enum(["info", "warning", "critical"]),
        entityType: z.string(),
        canonicalEntityId: z.string(),
        providerNames: z.array(z.string()),
        providerEntityIds: z.array(z.string()),
        trustedProvider: z.string().nullable(),
        dataQualityScoreDelta: z.number().max(0),
        evidenceJson: z.record(z.string(), z.unknown()).default({}),
        recommendedAction: z.string(),
      }),
    ),
    persistedEvents: z.array(
      z.object({
        providerConflictEventId: z.number().int().positive(),
        sourceReviewRunId: z.number().int().positive().nullable(),
        sourceIssueId: z.string().nullable(),
        conflictType: z.enum([
          "provider_mapping_conflict",
          "provider_observation_conflict",
        ]),
        severity: z.enum(["info", "warning", "critical"]),
        entityType: z.string(),
        canonicalEntityId: z.string(),
        providerNames: z.array(z.string()),
        providerEntityIds: z.array(z.string()),
        trustedProvider: z.string().nullable(),
        resolutionStatus: z.enum(["open", "resolved", "ignored"]),
        dataQualityScoreDelta: z.number().max(0),
        evidenceJson: z.record(z.string(), z.unknown()).default({}),
        recommendedAction: z.string(),
        requestedBy: z.string().nullable(),
        createdAtUtc: z.string(),
        resolvedAtUtc: z.string().nullable(),
      }),
    ),
    persistedOpenCount: z.number().int().nonnegative(),
    persistedResolvedCount: z.number().int().nonnegative(),
    persistedIgnoredCount: z.number().int().nonnegative(),
    stale: z.boolean(),
    fallbackUsed: z.boolean(),
  }),
  oddsCoverage: z.object({
    fetched: z.boolean(),
    competitionId: z.string(),
    competitionName: z.string(),
    fixtureCount: z.number().int().nonnegative(),
    oddsSnapshotCount: z.number().int().nonnegative(),
    bookmakerCount: z.number().int().nonnegative(),
    oddsCoverage: z.number().min(0).max(1),
    oneXTwoCoverage: z.number().min(0).max(1),
    handicapCoverage: z.number().min(0).max(1),
    freshOddsCoverage: z.number().min(0).max(1),
    marketTypes: z.array(z.string()),
    generatedAtUtc: z.string(),
    stale: z.boolean(),
    fallbackUsed: z.boolean(),
  }),
  oddsGapReport: z.object({
    fetched: z.boolean(),
    competitionId: z.string(),
    competitionName: z.string(),
    provider: z.string(),
    windowStartUtc: z.string(),
    asOfTimeUtc: z.string(),
    maxSnapshotLagHours: z.number().int().positive(),
    fixtureCount: z.number().int().nonnegative(),
    gapCount: z.number().int().nonnegative(),
    noOddsCount: z.number().int().nonnegative(),
    staleOddsCount: z.number().int().nonnegative(),
    providerEventUnavailableCount: z.number().int().nonnegative(),
    missing1x2Count: z.number().int().nonnegative(),
    missingHandicapCount: z.number().int().nonnegative(),
    unmappedFixtureCount: z.number().int().nonnegative(),
    mappedGapCount: z.number().int().nonnegative(),
    items: z.array(
      z.object({
        fixtureId: z.string(),
        competitionId: z.string(),
        competitionName: z.string(),
        kickoffTimeUtc: z.string(),
        homeTeamName: z.string(),
        awayTeamName: z.string(),
        issueTypes: z.array(
          z.enum([
            "no_odds",
            "missing_market",
            "stale_odds",
            "unmapped",
            "provider_event_unavailable",
          ]),
        ),
        recommendedAction: z.string(),
        oddsSnapshotCount: z.number().int().nonnegative(),
        bookmakerCount: z.number().int().nonnegative(),
        has1x2: z.boolean(),
        hasHandicap: z.boolean(),
        freshEnough: z.boolean(),
        latestSnapshotTimeUtc: z.string().nullable(),
        latestSnapshotLagHours: z.number().nonnegative().nullable(),
        marketTypes: z.array(z.string()),
        hasProviderMapping: z.boolean(),
        provider: z.string(),
        providerEventId: z.string().nullable(),
        providerMappingId: z.number().int().positive().nullable(),
        providerMappingConfidence: z.number().min(0).max(1).nullable(),
        providerMappingUpdatedAtUtc: z.string().nullable(),
        eventAvailabilityNote: z.string().nullable(),
        fallbackCandidates: z.array(
          z.object({
            providerName: z.string(),
            coverageRole: z.string(),
            adapterStatus: z.enum(["supported_now", "adapter_planned"]),
            requiredEnvVar: z.string(),
            recommendedAction: z.string(),
          }),
        ),
      }),
    ),
    generatedAtUtc: z.string(),
    stale: z.boolean(),
    fallbackUsed: z.boolean(),
  }),
  fallbackOddsProbe: z.object({
    fetched: z.boolean(),
    competitionId: z.string(),
    primaryProvider: z.string(),
    fallbackProvider: z.string(),
    liveProviderProbe: z.boolean(),
    providerKeyConfigured: z.boolean(),
    checkedGapCount: z.number().int().nonnegative(),
    providerEventUnavailableCount: z.number().int().nonnegative(),
    mappedFallbackCount: z.number().int().nonnegative(),
    probedFixtureCount: z.number().int().nonnegative(),
    recoverableFixtureCount: z.number().int().nonnegative(),
    normalizedOddsCount: z.number().int().nonnegative(),
    bookmakerCount: z.number().int().nonnegative(),
    marketTypes: z.array(z.string()),
    items: z.array(
      z.object({
        fixtureId: z.string(),
        competitionId: z.string(),
        kickoffTimeUtc: z.string(),
        homeTeamName: z.string(),
        awayTeamName: z.string(),
        primaryProvider: z.string(),
        fallbackProvider: z.string(),
        status: z.enum([
          "mapping_missing",
          "mapped_probe_ready",
          "covered",
          "mapped_no_supported_odds",
          "not_configured",
          "provider_auth_failed",
          "provider_limited",
          "provider_rate_limited",
          "provider_unavailable",
          "adapter_planned",
        ]),
        canRecoverGap: z.boolean(),
        providerFixtureId: z.string().nullable(),
        providerMappingId: z.number().int().positive().nullable(),
        providerMappingConfidence: z.number().min(0).max(1).nullable(),
        providerKeyConfigured: z.boolean(),
        liveProviderProbe: z.boolean(),
        normalizedOddsCount: z.number().int().nonnegative(),
        bookmakerCount: z.number().int().nonnegative(),
        marketTypes: z.array(z.string()),
        warnings: z.array(z.string()),
        recommendedAction: z.string(),
      }),
    ),
    warnings: z.array(z.string()),
    generatedAtUtc: z.string(),
    stale: z.boolean(),
    fallbackUsed: z.boolean(),
  }),
  providerSyncWorkflow: z.object({
    fetched: z.boolean(),
    runs: z.array(
      z.object({
        providerSyncWorkflowRunId: z.number().int().positive(),
        status: z.enum(["running", "completed", "failed"]),
        dryRun: z.boolean(),
        requestedBy: z.string().nullable(),
        startedAtUtc: z.string(),
        completedAtUtc: z.string().nullable(),
        durationMs: z.number().int().nonnegative().nullable(),
        fixtureSyncRunId: z.number().int().positive().nullable(),
        oddsSyncRunIds: z.array(z.number().int().positive()),
        availabilitySyncRunIds: z.array(z.number().int().positive()),
        fixtureCount: z.number().int().nonnegative(),
        oddsSnapshotCount: z.number().int().nonnegative(),
        availabilitySnapshotCount: z.number().int().nonnegative(),
        rawPayloadIds: z.array(z.number().int().positive()),
        canonicalFixtureIds: z.array(z.string()),
        prematchWorkflowRunId: z.number().int().positive().nullable(),
        warnings: z.array(z.string()),
        errorMessage: z.string().nullable(),
        metadataJson: z.record(z.string(), z.unknown()),
      }),
    ),
    templatesFetched: z.boolean(),
    templates: z.array(
      z.object({
        providerSyncWorkflowTemplateId: z.number().int().positive(),
        templateName: z.string(),
        description: z.string().nullable(),
        dryRun: z.boolean(),
        fixtureSync: z.record(z.string(), z.unknown()).nullable(),
        oddsSyncs: z.array(z.record(z.string(), z.unknown())),
        availabilitySyncs: z.array(z.record(z.string(), z.unknown())),
        runConflictDetection: z.boolean(),
        conflictObservationLookbackHours: z.number().int().positive(),
        conflictLimit: z.number().int().positive(),
        createdBy: z.string().nullable(),
        createdAtUtc: z.string(),
        updatedAtUtc: z.string(),
        archivedAtUtc: z.string().nullable(),
        archivedBy: z.string().nullable(),
        archiveReason: z.string().nullable(),
        metadataJson: z.record(z.string(), z.unknown()),
        preflightResult: z.object({
          valid: z.boolean(),
          taskCount: z.number().int().nonnegative(),
          syncTypes: z.array(z.string()),
          canonicalFixtureIds: z.array(z.string()),
          issueCount: z.number().int().nonnegative(),
          errorCount: z.number().int().nonnegative(),
          warningCount: z.number().int().nonnegative(),
          infoCount: z.number().int().nonnegative(),
          issues: z.array(
            z.object({
              severity: z.enum(["error", "warning", "info"]),
              code: z.string(),
              message: z.string(),
              fieldPath: z.string().nullable(),
            }),
          ),
          metadataJson: z.record(z.string(), z.unknown()),
        }),
      }),
    ),
    approvalsFetched: z.boolean(),
    approvals: z.array(
      z.object({
        providerSyncWorkflowApprovalId: z.number().int().positive(),
        approvalType: z.string(),
        approvalStatus: z.enum(["approved", "superseded", "revoked"]),
        providerSyncWorkflowTemplateId: z.number().int().positive().nullable(),
        providerSyncWorkflowRunId: z.number().int().positive().nullable(),
        approvedBy: z.string().nullable(),
        approvedAtUtc: z.string(),
        approvalNote: z.string().nullable(),
        requestPayloadJson: z.record(z.string(), z.unknown()),
        metadataJson: z.record(z.string(), z.unknown()),
      }),
    ),
    stale: z.boolean(),
    fallbackUsed: z.boolean(),
  }),
  predictionQualityGate: z.object({
    fetched: z.boolean(),
    runs: z.array(
      z.object({
        predictionJobRunId: z.number().int().positive(),
        jobType: z.enum([
          "mock_prematch_predictions",
          "canonical_prematch_predictions",
        ]),
        status: z.enum(["running", "completed", "failed"]),
        dryRun: z.boolean(),
        requestedBy: z.string().nullable(),
        startedAtUtc: z.string(),
        completedAtUtc: z.string().nullable(),
        durationMs: z.number().int().nonnegative().nullable(),
        fixtureCount: z.number().int().nonnegative(),
        generatedCount: z.number().int().nonnegative(),
        skippedFixtureIds: z.array(z.string()),
        warnings: z.array(z.string()),
        errorMessage: z.string().nullable(),
        dataQualityScores: z.record(z.string(), z.number().min(0).max(100)),
      }),
    ),
    latestRun: z
      .object({
        predictionJobRunId: z.number().int().positive(),
        jobType: z.enum([
          "mock_prematch_predictions",
          "canonical_prematch_predictions",
        ]),
        status: z.enum(["running", "completed", "failed"]),
        dryRun: z.boolean(),
        requestedBy: z.string().nullable(),
        startedAtUtc: z.string(),
        completedAtUtc: z.string().nullable(),
        durationMs: z.number().int().nonnegative().nullable(),
        fixtureCount: z.number().int().nonnegative(),
        generatedCount: z.number().int().nonnegative(),
        skippedFixtureIds: z.array(z.string()),
        warnings: z.array(z.string()),
        errorMessage: z.string().nullable(),
        dataQualityScores: z.record(z.string(), z.number().min(0).max(100)),
      })
      .nullable(),
    stale: z.boolean(),
    fallbackUsed: z.boolean(),
  }),
  latestAssessmentCount: z.number().int().nonnegative(),
  generatedAtUtc: z.string(),
  stale: z.boolean(),
  fallbackUsed: z.boolean(),
});
