"""Accuracy Learning Loop MVP helpers."""

from nutmeg.accuracy.calibration import (
    FileCalibrationBucketStore,
    calibration_bucket_key_for_probability,
)
from nutmeg.accuracy.calibration_evidence import (
    CalibrationEvidenceReport,
    PostgresCalibrationEvidenceRepository,
    build_calibration_evidence_report,
)
from nutmeg.accuracy.dixon_coles_backtest import (
    StoredDixonColesBacktestArtifacts,
    backtest_run_from_dixon_coles_training_report,
    calibration_json_from_dixon_coles_training_report,
    compare_dixon_coles_training_report_to_baseline,
    metrics_json_from_dixon_coles_training_report,
    model_metrics_from_dixon_coles_training_report,
    persist_dixon_coles_training_backtest,
)
from nutmeg.accuracy.dixon_coles_calibration import (
    DixonColesCalibrationBucket,
    DixonColesCalibrationObservation,
    DixonColesMatchCalibrationMetric,
    DixonColesValidationCalibrationReport,
    build_dixon_coles_validation_calibration_report,
)
from nutmeg.accuracy.dixon_coles_job import (
    DixonColesPromotionArtifacts,
    DixonColesTrainingBacktestJobOptions,
    DixonColesTrainingBacktestJobResult,
    build_dixon_coles_promotion_artifacts,
    list_dixon_coles_training_matches,
    run_dixon_coles_training_backtest_job,
)
from nutmeg.accuracy.error_classifier import classify_prediction_error
from nutmeg.accuracy.evaluator import evaluate_prediction_snapshot
from nutmeg.accuracy.factory import build_accuracy_repository
from nutmeg.accuracy.historical_poisson_parameter_admission import (
    HistoricalPoissonParameterAdmissionCheck,
    HistoricalPoissonParameterAdmissionOptions,
    HistoricalPoissonParameterAdmissionReport,
    build_historical_poisson_parameter_admission_report,
    load_historical_poisson_parameter_admission_report,
    load_historical_poisson_parameter_learning_report,
)
from nutmeg.accuracy.historical_poisson_parameter_learning import (
    HistoricalPoissonCompetitionParameterLearningResult,
    HistoricalPoissonParameterCandidate,
    HistoricalPoissonParameterCandidateTrainingResult,
    HistoricalPoissonParameterLearningOptions,
    HistoricalPoissonParameterLearningReport,
    build_historical_poisson_parameter_learning_report,
)
from nutmeg.accuracy.historical_poisson_prematch_lambda_admission import (
    HistoricalPoissonPrematchLambdaAdmissionCheck,
    HistoricalPoissonPrematchLambdaAdmissionOptions,
    HistoricalPoissonPrematchLambdaAdmissionReport,
    build_historical_poisson_prematch_lambda_admission_report,
    load_historical_poisson_prematch_lambda_admission_report,
)
from nutmeg.accuracy.historical_poisson_segmented_admission import (
    HistoricalPoissonCompetitionSegmentDecision,
    HistoricalPoissonSegmentedAdmissionCheck,
    HistoricalPoissonSegmentedAdmissionOptions,
    HistoricalPoissonSegmentedAdmissionReport,
    build_historical_poisson_segmented_admission_report,
    load_historical_poisson_segmented_admission_report,
)
from nutmeg.accuracy.historical_poisson_walk_forward import (
    HistoricalPoissonWalkForwardComparisonGroup,
    HistoricalPoissonWalkForwardFixtureSample,
    HistoricalPoissonWalkForwardMetricSet,
    HistoricalPoissonWalkForwardOptions,
    HistoricalPoissonWalkForwardReport,
    build_historical_poisson_walk_forward_report,
)
from nutmeg.accuracy.historical_prematch_feature_ablation import (
    HistoricalPrematchFeatureAblationComparisonGroup,
    HistoricalPrematchFeatureAblationFixtureSample,
    HistoricalPrematchFeatureAblationMetricSet,
    HistoricalPrematchFeatureAblationOptions,
    HistoricalPrematchFeatureAblationReport,
    build_historical_prematch_feature_ablation_report,
)
from nutmeg.accuracy.historical_prematch_feature_ablation_grid import (
    HistoricalPrematchFeatureAblationGridCandidate,
    HistoricalPrematchFeatureAblationGridOptions,
    HistoricalPrematchFeatureAblationGridReport,
    build_historical_prematch_feature_ablation_grid_report,
)
from nutmeg.accuracy.historical_prematch_feature_asian_handicap_calibration_sample_expansion import (  # noqa: E501
    HistoricalPrematchFeatureAsianHandicapCalibrationSampleExpansionCheck,
    HistoricalPrematchFeatureAsianHandicapCalibrationSampleExpansionOptions,
    HistoricalPrematchFeatureAsianHandicapCalibrationSampleExpansionReport,
    build_historical_prematch_feature_asian_handicap_calibration_sample_expansion_report,
    load_historical_prematch_feature_asian_handicap_calibration_sample_expansion_report,
)
from nutmeg.accuracy.historical_prematch_feature_asian_handicap_calibration_scope_refinement import (  # noqa: E501
    HistoricalPrematchFeatureAsianHandicapCalibrationScopeAlternative,
    HistoricalPrematchFeatureAsianHandicapCalibrationScopeRefinementCheck,
    HistoricalPrematchFeatureAsianHandicapCalibrationScopeRefinementOptions,
    HistoricalPrematchFeatureAsianHandicapCalibrationScopeRefinementReport,
    build_historical_prematch_feature_asian_handicap_calibration_scope_refinement_report,
    load_historical_prematch_feature_asian_handicap_calibration_scope_refinement_report,
)
from nutmeg.accuracy.historical_prematch_feature_asian_handicap_role_admission import (
    HistoricalPrematchFeatureAsianHandicapRoleAdmissionCheck,
    HistoricalPrematchFeatureAsianHandicapRoleAdmissionFold,
    HistoricalPrematchFeatureAsianHandicapRoleAdmissionOptions,
    HistoricalPrematchFeatureAsianHandicapRoleAdmissionReport,
    build_historical_prematch_feature_asian_handicap_role_admission_report,
    load_historical_prematch_feature_asian_handicap_role_admission_report,
)
from nutmeg.accuracy.historical_prematch_feature_asian_handicap_role_search import (
    HistoricalPrematchFeatureAsianHandicapRoleCandidate,
    HistoricalPrematchFeatureAsianHandicapRoleSearchOptions,
    HistoricalPrematchFeatureAsianHandicapRoleSearchReport,
    build_historical_prematch_feature_asian_handicap_role_search_report,
    load_historical_prematch_feature_asian_handicap_role_search_report,
)
from nutmeg.accuracy.historical_prematch_feature_asian_handicap_segment_refinement import (
    HistoricalPrematchFeatureAsianHandicapSegmentRefinementCheck,
    HistoricalPrematchFeatureAsianHandicapSegmentRefinementDecision,
    HistoricalPrematchFeatureAsianHandicapSegmentRefinementOptions,
    HistoricalPrematchFeatureAsianHandicapSegmentRefinementReport,
    build_historical_prematch_feature_asian_handicap_segment_refinement_report,
    load_historical_prematch_feature_asian_handicap_segment_refinement_report,
)
from nutmeg.accuracy.historical_prematch_feature_asian_handicap_segmented_admission import (
    HistoricalPrematchFeatureAsianHandicapSegmentCheck,
    HistoricalPrematchFeatureAsianHandicapSegmentDecision,
    HistoricalPrematchFeatureAsianHandicapSegmentedAdmissionOptions,
    HistoricalPrematchFeatureAsianHandicapSegmentedAdmissionReport,
    build_historical_prematch_feature_asian_handicap_segmented_admission_report,
    load_historical_prematch_feature_asian_handicap_segmented_admission_report,
)
from nutmeg.accuracy.historical_prematch_feature_asian_handicap_segmented_governance_review import (  # noqa: E501
    HistoricalPrematchFeatureAsianHandicapSegmentedGovernanceReviewCheck,
    HistoricalPrematchFeatureAsianHandicapSegmentedGovernanceReviewEvidence,
    HistoricalPrematchFeatureAsianHandicapSegmentedGovernanceReviewOptions,
    HistoricalPrematchFeatureAsianHandicapSegmentedGovernanceReviewReport,
    build_historical_prematch_feature_asian_handicap_segmented_governance_review_report,
    load_historical_prematch_feature_asian_handicap_segmented_governance_review_report,
)
from nutmeg.accuracy.historical_prematch_feature_parameter_learning import (
    HistoricalPrematchFeatureCompetitionParameterLearningResult,
    HistoricalPrematchFeatureParameterCandidate,
    HistoricalPrematchFeatureParameterCandidateTrainingResult,
    HistoricalPrematchFeatureParameterLearningOptions,
    HistoricalPrematchFeatureParameterLearningReport,
    build_historical_prematch_feature_parameter_learning_report,
)
from nutmeg.accuracy.historical_prematch_feature_shadow_comparison import (
    HistoricalPrematchFeatureShadowComparisonOptions,
    HistoricalPrematchFeatureShadowComparisonReport,
    HistoricalPrematchFeatureShadowMetricDelta,
    build_historical_prematch_feature_shadow_comparison_report,
)
from nutmeg.accuracy.historical_probability_calibration import (
    HistoricalProbabilityCalibrationBucket,
    HistoricalProbabilityCalibrationGroup,
    HistoricalProbabilityCalibrationOptions,
    HistoricalProbabilityCalibrationReport,
    build_historical_probability_calibration_report,
)
from nutmeg.accuracy.historical_probability_calibration_transform import (
    HistoricalProbabilityCalibrationTransformBucket,
    HistoricalProbabilityCalibrationTransformCompetitionResult,
    HistoricalProbabilityCalibrationTransformFixtureSample,
    HistoricalProbabilityCalibrationTransformMetricSet,
    HistoricalProbabilityCalibrationTransformOptions,
    HistoricalProbabilityCalibrationTransformReport,
    build_historical_probability_calibration_transform_report,
)
from nutmeg.accuracy.local_postgres_runner import (
    LocalAccuracyLoopRun,
    run_mock_accuracy_postgres_e2e,
)
from nutmeg.accuracy.metrics import (
    actual_score_probability,
    brier_score_1x2,
    expected_total_goals,
    log_loss,
    log_loss_1x2,
    score_rank,
)
from nutmeg.accuracy.mock_repository import ACTIVE_MODEL_VERSION, MockAccuracyEventRepository
from nutmeg.accuracy.model_comparison import compare_model_versions_stub
from nutmeg.accuracy.postgres_repository import PostgresAccuracyRepository
from nutmeg.accuracy.postgres_write_repository import PostgresAccuracyWriteRepository
from nutmeg.accuracy.promotion_evidence import (
    HandicapPerformanceEvidenceReport,
    ModelPromotionEvidenceBundle,
    ParlaySimulationEvidenceReport,
    PostgresPromotionEvidenceRepository,
    UpsetPrecisionEvidenceReport,
    build_handicap_performance_evidence_report,
    build_parlay_simulation_evidence_report,
    build_upset_precision_evidence_report,
)
from nutmeg.accuracy.repository import AccuracyRepository, AccuracySummaryService
from nutmeg.accuracy.summary import (
    AccuracyEvaluationEvent,
    CalibrationObservation,
    build_accuracy_summary,
)
from nutmeg.accuracy.weekly_training import (
    WeeklyDixonColesTrainingPipelineOptions,
    WeeklyDixonColesTrainingPipelineResult,
    WeeklyTrainingPipelinePlan,
    build_weekly_training_pipeline_plan,
    run_weekly_dixon_coles_training_pipeline,
    weekly_training_plan_metadata,
)
from nutmeg.accuracy.workflow import (
    AccuracyWriteRepository,
    evaluate_and_persist_post_match_result,
    one_x_two_calibration_observations,
)

__all__ = [
    "ACTIVE_MODEL_VERSION",
    "AccuracyEvaluationEvent",
    "AccuracyRepository",
    "AccuracySummaryService",
    "AccuracyWriteRepository",
    "CalibrationObservation",
    "CalibrationEvidenceReport",
    "DixonColesPromotionArtifacts",
    "DixonColesCalibrationBucket",
    "DixonColesCalibrationObservation",
    "DixonColesMatchCalibrationMetric",
    "DixonColesTrainingBacktestJobOptions",
    "DixonColesTrainingBacktestJobResult",
    "DixonColesValidationCalibrationReport",
    "FileCalibrationBucketStore",
    "LocalAccuracyLoopRun",
    "MockAccuracyEventRepository",
    "PostgresAccuracyRepository",
    "PostgresAccuracyWriteRepository",
    "PostgresCalibrationEvidenceRepository",
    "PostgresPromotionEvidenceRepository",
    "HandicapPerformanceEvidenceReport",
    "HistoricalProbabilityCalibrationBucket",
    "HistoricalProbabilityCalibrationGroup",
    "HistoricalProbabilityCalibrationOptions",
    "HistoricalProbabilityCalibrationReport",
    "HistoricalProbabilityCalibrationTransformBucket",
    "HistoricalProbabilityCalibrationTransformCompetitionResult",
    "HistoricalProbabilityCalibrationTransformFixtureSample",
    "HistoricalProbabilityCalibrationTransformMetricSet",
    "HistoricalProbabilityCalibrationTransformOptions",
    "HistoricalProbabilityCalibrationTransformReport",
    "HistoricalPoissonCompetitionParameterLearningResult",
    "HistoricalPoissonParameterAdmissionCheck",
    "HistoricalPoissonParameterAdmissionOptions",
    "HistoricalPoissonParameterAdmissionReport",
    "HistoricalPoissonParameterCandidate",
    "HistoricalPoissonParameterCandidateTrainingResult",
    "HistoricalPoissonParameterLearningOptions",
    "HistoricalPoissonParameterLearningReport",
    "HistoricalPoissonPrematchLambdaAdmissionCheck",
    "HistoricalPoissonPrematchLambdaAdmissionOptions",
    "HistoricalPoissonPrematchLambdaAdmissionReport",
    "HistoricalPoissonCompetitionSegmentDecision",
    "HistoricalPoissonSegmentedAdmissionCheck",
    "HistoricalPoissonSegmentedAdmissionOptions",
    "HistoricalPoissonSegmentedAdmissionReport",
    "HistoricalPoissonWalkForwardComparisonGroup",
    "HistoricalPoissonWalkForwardFixtureSample",
    "HistoricalPoissonWalkForwardMetricSet",
    "HistoricalPoissonWalkForwardOptions",
    "HistoricalPoissonWalkForwardReport",
    "HistoricalPrematchFeatureAblationComparisonGroup",
    "HistoricalPrematchFeatureAblationFixtureSample",
    "HistoricalPrematchFeatureAblationMetricSet",
    "HistoricalPrematchFeatureAblationOptions",
    "HistoricalPrematchFeatureAblationReport",
    "HistoricalPrematchFeatureAblationGridCandidate",
    "HistoricalPrematchFeatureAblationGridOptions",
    "HistoricalPrematchFeatureAblationGridReport",
    "HistoricalPrematchFeatureAsianHandicapCalibrationSampleExpansionCheck",
    "HistoricalPrematchFeatureAsianHandicapCalibrationSampleExpansionOptions",
    "HistoricalPrematchFeatureAsianHandicapCalibrationSampleExpansionReport",
    "HistoricalPrematchFeatureAsianHandicapCalibrationScopeAlternative",
    "HistoricalPrematchFeatureAsianHandicapCalibrationScopeRefinementCheck",
    "HistoricalPrematchFeatureAsianHandicapCalibrationScopeRefinementOptions",
    "HistoricalPrematchFeatureAsianHandicapCalibrationScopeRefinementReport",
    "HistoricalPrematchFeatureAsianHandicapRoleAdmissionCheck",
    "HistoricalPrematchFeatureAsianHandicapRoleAdmissionFold",
    "HistoricalPrematchFeatureAsianHandicapRoleAdmissionOptions",
    "HistoricalPrematchFeatureAsianHandicapRoleAdmissionReport",
    "HistoricalPrematchFeatureAsianHandicapRoleCandidate",
    "HistoricalPrematchFeatureAsianHandicapRoleSearchOptions",
    "HistoricalPrematchFeatureAsianHandicapRoleSearchReport",
    "HistoricalPrematchFeatureAsianHandicapSegmentRefinementCheck",
    "HistoricalPrematchFeatureAsianHandicapSegmentRefinementDecision",
    "HistoricalPrematchFeatureAsianHandicapSegmentRefinementOptions",
    "HistoricalPrematchFeatureAsianHandicapSegmentRefinementReport",
    "HistoricalPrematchFeatureAsianHandicapSegmentCheck",
    "HistoricalPrematchFeatureAsianHandicapSegmentDecision",
    "HistoricalPrematchFeatureAsianHandicapSegmentedAdmissionOptions",
    "HistoricalPrematchFeatureAsianHandicapSegmentedAdmissionReport",
    "HistoricalPrematchFeatureAsianHandicapSegmentedGovernanceReviewCheck",
    "HistoricalPrematchFeatureAsianHandicapSegmentedGovernanceReviewEvidence",
    "HistoricalPrematchFeatureAsianHandicapSegmentedGovernanceReviewOptions",
    "HistoricalPrematchFeatureAsianHandicapSegmentedGovernanceReviewReport",
    "HistoricalPrematchFeatureCompetitionParameterLearningResult",
    "HistoricalPrematchFeatureParameterCandidate",
    "HistoricalPrematchFeatureParameterCandidateTrainingResult",
    "HistoricalPrematchFeatureParameterLearningOptions",
    "HistoricalPrematchFeatureParameterLearningReport",
    "HistoricalPrematchFeatureShadowComparisonOptions",
    "HistoricalPrematchFeatureShadowComparisonReport",
    "HistoricalPrematchFeatureShadowMetricDelta",
    "StoredDixonColesBacktestArtifacts",
    "ModelPromotionEvidenceBundle",
    "ParlaySimulationEvidenceReport",
    "UpsetPrecisionEvidenceReport",
    "WeeklyDixonColesTrainingPipelineOptions",
    "WeeklyDixonColesTrainingPipelineResult",
    "WeeklyTrainingPipelinePlan",
    "actual_score_probability",
    "backtest_run_from_dixon_coles_training_report",
    "build_accuracy_summary",
    "build_accuracy_repository",
    "build_calibration_evidence_report",
    "build_dixon_coles_promotion_artifacts",
    "build_dixon_coles_validation_calibration_report",
    "build_handicap_performance_evidence_report",
    "build_historical_poisson_parameter_admission_report",
    "build_historical_poisson_parameter_learning_report",
    "build_historical_poisson_prematch_lambda_admission_report",
    "build_historical_poisson_segmented_admission_report",
    "build_historical_probability_calibration_report",
    "build_historical_probability_calibration_transform_report",
    "build_historical_poisson_walk_forward_report",
    "build_historical_prematch_feature_ablation_report",
    "build_historical_prematch_feature_ablation_grid_report",
    "build_historical_prematch_feature_asian_handicap_calibration_sample_expansion_report",
    "build_historical_prematch_feature_asian_handicap_calibration_scope_refinement_report",
    "build_historical_prematch_feature_asian_handicap_role_admission_report",
    "build_historical_prematch_feature_asian_handicap_role_search_report",
    "build_historical_prematch_feature_asian_handicap_segment_refinement_report",
    "build_historical_prematch_feature_asian_handicap_segmented_admission_report",
    "build_historical_prematch_feature_asian_handicap_segmented_governance_review_report",
    "build_historical_prematch_feature_parameter_learning_report",
    "build_historical_prematch_feature_shadow_comparison_report",
    "build_parlay_simulation_evidence_report",
    "build_upset_precision_evidence_report",
    "build_weekly_training_pipeline_plan",
    "brier_score_1x2",
    "calibration_json_from_dixon_coles_training_report",
    "calibration_bucket_key_for_probability",
    "classify_prediction_error",
    "compare_dixon_coles_training_report_to_baseline",
    "compare_model_versions_stub",
    "evaluate_prediction_snapshot",
    "evaluate_and_persist_post_match_result",
    "expected_total_goals",
    "log_loss",
    "log_loss_1x2",
    "list_dixon_coles_training_matches",
    "load_historical_poisson_parameter_admission_report",
    "load_historical_poisson_parameter_learning_report",
    "load_historical_poisson_prematch_lambda_admission_report",
    "load_historical_poisson_segmented_admission_report",
    "load_historical_prematch_feature_asian_handicap_calibration_sample_expansion_report",
    "load_historical_prematch_feature_asian_handicap_calibration_scope_refinement_report",
    "load_historical_prematch_feature_asian_handicap_role_admission_report",
    "load_historical_prematch_feature_asian_handicap_role_search_report",
    "load_historical_prematch_feature_asian_handicap_segment_refinement_report",
    "load_historical_prematch_feature_asian_handicap_segmented_admission_report",
    "load_historical_prematch_feature_asian_handicap_segmented_governance_review_report",
    "metrics_json_from_dixon_coles_training_report",
    "model_metrics_from_dixon_coles_training_report",
    "one_x_two_calibration_observations",
    "persist_dixon_coles_training_backtest",
    "run_dixon_coles_training_backtest_job",
    "run_weekly_dixon_coles_training_pipeline",
    "run_mock_accuracy_postgres_e2e",
    "score_rank",
    "weekly_training_plan_metadata",
]
