#!/usr/bin/env bash
set -euo pipefail

TARGET="${NUTMEG_DEPLOY_TARGET:-root@156.236.76.121}"
REMOTE_DIR="${NUTMEG_REMOTE_DIR:-/opt/nutmeg}"
LIVE_PROBE="${NUTMEG_PROVIDER_RUNTIME_LIVE_PROBE:-false}"
RECORD_INCIDENT="${NUTMEG_PROVIDER_RUNTIME_RECORD_INCIDENT:-true}"
INCIDENT_THRESHOLD="${NUTMEG_PROVIDER_RUNTIME_INCIDENT_THRESHOLD:-P1}"

ssh -o BatchMode=yes "$TARGET" bash -s -- \
  "$REMOTE_DIR" "$LIVE_PROBE" "$RECORD_INCIDENT" "$INCIDENT_THRESHOLD" <<'REMOTE'
set -euo pipefail

REMOTE_DIR="$1"
LIVE_PROBE="$2"
RECORD_INCIDENT="$3"
INCIDENT_THRESHOLD="$4"
cd "$REMOTE_DIR"

NUTMEG_PROVIDER_RUNTIME_LIVE_PROBE="$LIVE_PROBE" \
NUTMEG_PROVIDER_RUNTIME_RECORD_INCIDENT="$RECORD_INCIDENT" \
NUTMEG_PROVIDER_RUNTIME_INCIDENT_THRESHOLD="$INCIDENT_THRESHOLD" \
  scripts/provider-runtime-monitoring-local.sh "$REMOTE_DIR"
REMOTE
